### ISSUE TITLE
Connect `fly.io` hosting with `squarespace` domain

### ISSUE THREAD

**Issue by MgenGlder** [dearborn-coding-club/website-base-backend#16]
## Summary
- Now that we've [decided on a hosting solution and deployed successfully](https://github.com/dearborn-coding-club/website-base-backend/issues/10) to it (see https://website-base-backend.fly.dev/ using [fly.io](https://fly.io)) we can start thinking about connecting the hosted microservice to the domain at `dearborncodingclub.com`.

**Comment by MgenGlder** [comment]
After the issues from last week, I've managed to add an `A` ip record to the DNS configuration in squarespace using the `66.241.125.104` app ip. It will take 24-48 hours to propagate through DNS, but I'm expecting `dearborncodingclub.com` to work by Saturday 🤞 .

**Comment by dXu23** [comment]
Since the website is up now, might as well close the issue.
