### ISSUE TITLE
[Idea] Come up with a logo for the website

### ISSUE THREAD

**Issue by MgenGlder** [dearborn-coding-club/website-base-backend#22]
## Description
- It would be nice to come up with a logo to use with the website.
    - An initial idea is to utilize the [anime.js framework](https://animejs.com/) to make a hand-drawn logo like what is done [here](https://codepen.io/juliangarnier/pen/oZNYXB).

**Comment by gonzalolanderos** [comment]
A couple of ideas (we can tweak them later): 
![dcc-2](https://github.com/dearborn-coding-club/website-base-backend/assets/12752986/72115930-2b65-4385-895b-975256ab2d73)
![dcc](https://github.com/dearborn-coding-club/website-base-backend/assets/12752986/f28a8036-1f8c-42c8-8e5f-45f6bb0ba4bb)

**Comment by dXu23** [comment]
![dcc_dark](https://github.com/dearborn-coding-club/website-base-backend/assets/31428760/98d087e8-2835-4ae2-af40-89742339e8b5)

Here's my attempt at logo design lol.
