### ISSUE TITLE
[Idea] Create a slack channel

### ISSUE THREAD

**Issue by MgenGlder** [dearborn-coding-club/website-base-backend#24]
## Summary
It might be a good idea to set up a slack channel for ourselves where we can chat live when it makes sense. It might also be too early so open to feedback/perspective. It also sets us up to use [chatops](https://hubot.github.com/) if we can figure out how to set it up.

**Comment by BLD-1984** [comment]
Created at https://dearborncodingclub.slack.com/ 

@MgenGlder I sent you an invite and made you an Owner. 

Here is a join link (will work through the end of June) @MgenGlder you want to share with the group? 
https://join.slack.com/t/dearborncodingclub/shared_invite/zt-2jya0limd-A~pWwbV5eDMEdd0ee8Gu9g

**Comment by MgenGlder** [comment]
Awesome! Thanks for setting this up 🙏 - I was able to join successfully. I'll look to get folks added to it so we can start using it.

**Comment by Duke242** [comment]
Slack channel is opened!
