### ISSUE TITLE
[Idea] Set up deployment pipeline for non-production instance

### ISSUE THREAD

**Issue by MgenGlder** [dearborn-coding-club/website-base-backend#25]

**Comment by Br-Jr** [comment]
I suggest we use either a spot instance or ecs within aws.

**Comment by Br-Jr** [comment]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html#:~:text=To%20use%20Spot%20Instances%2C%20you,until%20you%20cancel%20the%20request.

**Comment by Br-Jr** [comment]
Another quick suggestion, if we decide to go this route we should deploy the infrastructure in terraform. That way we can easily spin up, destroy or make updates to the enviroment

**Comment by Br-Jr** [comment]
- [ ] Create a S3 Bucket in Terraform to Statically Host HTML and CSS Files
- [ ] Create a GitHub action workflow that points to the S3 bucket for development

**Comment by MgenGlder** [comment]
This works now- closing for now.
